"""add org id to deployments

Revision ID: 7bccb5021891
Revises: 22b49dd64768
Create Date: 2020-08-28 17:22:55.322739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bccb5021891'
down_revision = '22b49dd64768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('organization_id', sa.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'deployments', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'organization_id')
    # ### end Alembic commands ###
