"""test migration

Revision ID: e170c5184a06
Revises: 1fe49bc5ee7c
Create Date: 2020-08-28 16:40:22.478409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e170c5184a06'
down_revision = '1fe49bc5ee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_repo_data_records',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('parent_git_repo_id', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repo_uri', sa.TEXT(), nullable=False),
    sa.Column('repo_uri_html', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_git_repo_id'], ['git_repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_git_repo_data_record__git_repo_id__timestamp', 'git_repo_data_records', ['parent_git_repo_id', 'timestamp'], unique=True)
    op.add_column('aws_accounts', sa.Column('account_label_two', sa.Text(), nullable=True))
    op.add_column('git_repos', sa.Column('organization_id', sa.TEXT(), nullable=False))
    op.add_column('git_repos', sa.Column('repo_data_record_id', sa.TEXT(), nullable=False))
    op.create_index('idx_git_repo__organization', 'git_repos', ['organization_id', 'id'], unique=True)
    op.drop_constraint('git_repos_project_id_fkey', 'git_repos', type_='foreignkey')
    op.create_foreign_key(None, 'git_repos', 'organizations', ['organization_id'], ['id'])
    op.drop_column('git_repos', 'url')
    op.drop_column('git_repos', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_repos', sa.Column('project_id', sa.CHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('git_repos', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'git_repos', type_='foreignkey')
    op.create_foreign_key('git_repos_project_id_fkey', 'git_repos', 'projects', ['project_id'], ['id'])
    op.drop_index('idx_git_repo__organization', table_name='git_repos')
    op.drop_column('git_repos', 'repo_data_record_id')
    op.drop_column('git_repos', 'organization_id')
    op.drop_column('aws_accounts', 'account_label_two')
    op.drop_index('idx_git_repo_data_record__git_repo_id__timestamp', table_name='git_repo_data_records')
    op.drop_table('git_repo_data_records')
    # ### end Alembic commands ###
