kind: Service
apiVersion: v1
metadata:
  name: refinery-api-server
  namespace: refinery
  labels:
    k8s-app: refinery-api-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.apiServer.ports.http.port }}
      targetPort: {{ .Values.apiServer.ports.http.targetPort }}
  selector:
    k8s-app: refinery-api-server
  type: ClusterIP
  sessionAffinity: None
