apiVersion: v1
kind: ConfigMap
metadata:
  name: refinery-api-config-files
  namespace: refinery
data:
  production.yaml: |
    config:
      debug: {{ .Values.apiServer.debug }}

      # Instance URL, used for sending emails, etc.
      web_origin: {{ .Values.frontEnd.origin }}

      # The HTTP origin to serve in Access-Control-Allow-Origin header
      access_control_allow_origins: {{ mustToJson .Values.apiServer.config.accessControlAllowOrigins }}

      # Shared secret for /service/ endpoints to be triggered
      service_shared_secret: {{ .Values.secrets.serviceSharedSecret }}

      # AWS Configuration
      region_name: us-west-2
      aws_access_key: {{ .Values.secrets.awsAccessKey }}
      aws_secret_key: {{ .Values.secrets.awsSecretKey }}
      aws_account_id: {{ .Values.aws.accountID }}

      # Workflow Manager
      workflow_manager_api_url: {{ .Values.workflowManager.url }}

      # Postgresql
      postgreql_username: {{ .Values.postgresql.username }}
      postgreql_password: {{ .Values.postgresql.password }}
      postgres_db: {{ .Values.postgresql.postgresqlDatabase }}
      postgresql_host: {{ .Values.postgresql.host }}

      # Legacy values
      lambda_redis_hostname: {{ .Values.lambdaRedis.hostname }}
      lambda_redis_port: {{ .Values.lambdaRedis.port }}
      lambda_redis_password: {{ .Values.lambdaRedis.password }}

      # Mailgun
      mailgun_api_key: {{ .Values.secrets.mailgunApiKey }}

      # Stripe
      stripe_api_key: {{ .Values.secrets.stripeApiKey }}

      # Intercom
      intercom_hmac_secret: {{ .Values.secrets.intercomHMACSecret }}

      # Github
      github_client_id: {{ .Values.secrets.githubClientID }}
      github_client_secret: {{ .Values.secrets.githubClientSecret }}

      # Cookies
      # How long the email token should last before expiring
      email_token_lifetime: 10800 # 3 hours before the email authentication token no longer works
      # Secret value for the HMACed cookies
      # How many days the HTTP cookies last for
      cookie_expire_days: 30
      cookie_secret_value: {{ .Values.secrets.cookieSecretValue }}

      # Ngrok (used for development)
      ngrok_api_secret: {{ .Values.secrets.ngrokApiSecret }}
      ngrok_enabled: {{ .Values.ngrok.enabled }}

      # AWS Roles and resources
      lambda_role: {{ .Values.aws.resources.lambdaRole }} # Use the install/setup_aws_account.py script to get this
      events_role: {{ .Values.aws.resources.eventsRole }} # Use the install/setup_aws_account.py script to get this
      tmp_lambda_packages_bucket: {{ .Values.aws.resources.tmpLambdaPackagesBucket }} # Use the install/setup_aws_account.py script to get this
      pipeline_logs_bucket: {{ .Values.aws.resources.pipelineLogsBucket }} # Use the install/setup_aws_account.py script to get this
      # The IAM role we have in all customer accounts so we can administrate them
      # This should only be changed when this is run in dev VS prod. Otherwise this
      # value should never change
      customer_aws_admin_assume_role: {{ .Values.aws.resources.customerAwsAdminAssumeRole }}

      # This specifies the max time for the assume role action
      # We have a per-account ceiling of 1-hour, but we should basically always
      # be assuming for less time than that.
      assume_role_session_lifetime_seconds: "900"

      # The prefix for customer AWS accounts
      customer_aws_email_prefix: "aws-"
      # The target amount of AWS accounts in the pool, these are the
      # AWS accounts which are frozen for customers to start using.
      reserved_aws_pool_target_amount: 2
      vpc_data: "{}"

      ### Billing ###
      # How much we mark up AWS's costs for managed AWS accounts
      mark_up_percent: 20
      # Whether to finalize invoices or leave them in draft for manual approval
      # and final sending.
      stripe_finalize_invoices: "false"
      # The free-trial account maxi3551f01e7fb3mum amount that a account is allowed
      # to incur before the account is frozen.
      free_trial_billing_limit: "10.00"

      ### SES Configuration ###
      ses_emails_from_email: admin@pimpmysg.com
      ses_region: us-west-2
      ses_reply_to: admin@pimpmysg.com

      ### Email addresses ###
      # The email address which is notified when we have an hour to review the
      # invoices before they go out.
      billing_alert_email: {{ .Values.apiServer.config.billingAlertEmail }}
      # Mailgun for sending email
      # The email suffix for customer AWS accounts
      customer_aws_email_suffix: {{ .Values.apiServer.config.customerAwsEmailSuffix }}
      # The send from email
      from_email: {{ .Values.apiServer.config.fromEmail }}
      # Alerts for when a free-trial account goes over the limit
      alerts_email: {{ .Values.apiServer.config.alertsEmail }}
      # Alerts for when a free-trial account goes over the limit
      free_trial_freeze_alerts: {{ .Values.apiServer.config.freeTrialFreezeAlerts }}
      # Place where to receive signup emails
      internal_signup_notification_email: {{ .Values.apiServer.config.internalSignupNotificationEmail }}

