kind: Service
apiVersion: v1
metadata:
  name: workflow-manager
  labels:
    k8s-app: workflow-manager
  annotations:
    description: Manage Refinery workflows
spec:
  ports:
    - name: http 
      protocol: TCP
      port: {{ .Values.workflowManager.ports.http.port }}
      targetPort: {{ .Values.workflowManager.ports.http.targetPort }}
  selector:
    k8s-app: workflow-manager
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

