#!/usr/bin/env bash
if [ -z "$GEM_HOME" ]; then
    export GEM_HOME=/var/task/installed_gems/ruby/2.6.0
fi

if [ -z "$GEM_PATH" ]; then
    export GEM_PATH=/var/task/installed_gems/ruby/2.6.0:/var/task/vendor/bundle/ruby/2.6.0:/opt/ruby/gems/2.6.0:/opt/ruby/lib/ruby/gems/2.6.0
fi

if [ -z "$AWS_EXECUTION_ENV" ]; then
    export AWS_EXECUTION_ENV=AWS_Lambda_custom_ruby2.6.4
fi

if [ -z "$RUBYLIB" ]; then
    export RUBYLIB=/var/task:/var/runtime/lib:/opt/ruby/lib
else
    export RUBYLIB=/var/task:/var/runtime/lib:$RUBYLIB
fi

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/lib64"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$DIR/ruby/bin/ruby "$@"