version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=134071937287.dkr.ecr.us-west-2.amazonaws.com/refinery-api-server-prod
      - REPOSITORY_NGINX_URI=134071937287.dkr.ecr.us-west-2.amazonaws.com/refinery-nginx-server
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker login --username freeqaz --password 62e6d27d-9cc3-4c3a-b7d2-af0f824ea370
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Refinery API server Docker image...
      - docker build -t $REPOSITORY_URI:latest ./api/
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - cd front-end
      - ./build/build-production-assets.sh
      - mv front-end-dist ../nginx-container/front-end-dist
      - cd ..
      - docker build -t $REPOSITORY_NGINX_URI:latest ./nginx-container/
      - docker tag $REPOSITORY_NGINX_URI:latest $REPOSITORY_NGINX_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker API server images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_NGINX_URI:latest
      - docker push $REPOSITORY_NGINX_URI:$IMAGE_TAG
artifacts:
    base-directory: elasticbeanstalk-config/
    files: "**/*"