version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=134071937287.dkr.ecr.us-west-2.amazonaws.com
      - API_SERVER_REPO=$REPOSITORY_URI/refinery-api-server-prod
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Refinery API server Docker image...
      - docker build -t $API_SERVER_REPO:latest ./api/
      - docker tag $API_SERVER_REPO:latest $API_SERVER_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker API server image...
      - docker push $API_SERVER_REPO:latest
      - docker push $API_SERVER_REPO:$IMAGE_TAG
