version: 0.2

env:
  exported-variables:
    - REPOSITORY_URI
    - AWS_DEFAULT_REGION
    - CODEBUILD_RESOLVED_SOURCE_VERSION
  secrets-manager:
    DOCKER_USERNAME: refinery-secrets-kubes-prod:DOCKER_USERNAME
    DOCKER_PASSWORD: refinery-secrets-kubes-prod:DOCKER_PASSWORD

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - WORKFLOW_MANAGER_REPO=$REPOSITORY_URI/workflow-manager
      - WORKFLOW_MANAGER_WORKER_REPO=$REPOSITORY_URI/workflow-manager-worker
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`

      - echo Logging into DockerHub...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - echo Building the Refinery Workflow Manager Docker image...
      - docker build -t $WORKFLOW_MANAGER_REPO:$IMAGE_TAG -f ./golang/docker/Dockerfile.workflow-manager ./golang

      - echo Building the Refinery Workflow Manager Worker Docker image...
      - docker build -t $WORKFLOW_MANAGER_WORKER_REPO:$IMAGE_TAG -f ./golang/docker/Dockerfile.workflow-manager-worker ./golang
  post_build:
    commands:
      - echo Build completed on `date`

      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo Pushing the Refinery Workflow Manager Docker image...
      - docker push $WORKFLOW_MANAGER_REPO:$IMAGE_TAG
      - docker tag $WORKFLOW_MANAGER_REPO:$IMAGE_TAG $WORKFLOW_MANAGER_REPO:latest
      - docker push $WORKFLOW_MANAGER_REPO:latest

      - echo Pushing the Refinery Workflow Manager Worker Docker image...
      - docker push $WORKFLOW_MANAGER_WORKER_REPO:$IMAGE_TAG
      - docker tag $WORKFLOW_MANAGER_WORKER_REPO:$IMAGE_TAG $WORKFLOW_MANAGER_WORKER_REPO:latest
      - docker push $WORKFLOW_MANAGER_WORKER_REPO:latest
