version: 0.2

env:
  exported-variables:
    - REPOSITORY_URI
    - AWS_DEFAULT_REGION
    - CODEBUILD_RESOLVED_SOURCE_VERSION
    - CLOUDFRONT_URL
    - S3_DEPLOY_REGION
    - S3_DEPLOY_BUCKET
    - S3_DEPLOY_PATH
    - APP_API_URL

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt update
      - apt install -y awscli git python3
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - FRONT_END_REPO=$REPOSITORY_URI/refinery-nginx-server-kubes
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`

      - echo Building the Refinery Frontend...
      - cd ./front-end
      - ./build/build-production-assets.sh
      - mv front-end-dist ../nginx-container/front-end-dist
      - cd ..
      - docker build -t $FRONT_END_REPO:$IMAGE_TAG ./nginx-container/
  post_build:
    commands:
      - cd ./helm/refinery
      - echo Build completed on `date`

      - echo Pushing the Docker front end image...
      - docker push $FRONT_END_REPO:$IMAGE_TAG
