version: 0.2

env:
  exported-variables:
    - REPOSITORY_URI
    - AWS_DEFAULT_REGION
    - CODEBUILD_RESOLVED_SOURCE_VERSION
  secrets-manager:
    DOCKER_USERNAME: refinery-secrets-kubes-prod:DOCKER_USERNAME
    DOCKER_PASSWORD: refinery-secrets-kubes-prod:DOCKER_PASSWORD

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - API_SERVER_REPO=$REPOSITORY_URI/refinery-api-server-kubes
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`

      - echo Logging into DockerHub...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - echo Building the Refinery API server Docker image...
      - docker build -t $API_SERVER_REPO:$IMAGE_TAG ./api/
  post_build:
    commands:
      - echo Build completed on `date`

      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo Pushing the Docker API server image...
      - docker push $API_SERVER_REPO:$IMAGE_TAG
