version: 0.2

env:
  exported-variables:
    - REPOSITORY_URI
    - AWS_DEFAULT_REGION
    - CODEBUILD_RESOLVED_SOURCE_VERSION
  secrets-manager:
    DOCKER_USERNAME: refinery-secrets-kubes-prod:DOCKER_USERNAME
    DOCKER_PASSWORD: refinery-secrets-kubes-prod:DOCKER_PASSWORD

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt update
      - apt install -y awscli git python3
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - API_SERVER_REPO=$REPOSITORY_URI/refinery-api-server-kubes
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`

      - echo Building the Refinery API server Docker image...
      - docker build -t $API_SERVER_REPO:latest ./api/
      - docker tag $API_SERVER_REPO:latest $API_SERVER_REPO:$IMAGE_TAG
  post_build:
    commands:
      - cd ./helm/refinery
      - echo Build completed on `date`

      - echo Pushing the Docker API server image...
      - docker push $API_SERVER_REPO:latest
      - docker push $API_SERVER_REPO:$IMAGE_TAG
