version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=134071937287.dkr.ecr.us-west-2.amazonaws.com
      - FRONT_END_REPO=$REPOSITORY_URI/refinery-nginx-server-kubes
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - cd front-end
      - ./build/build-production-assets.sh
      - mv front-end-dist ../nginx-container/front-end-dist
      - cd ..
      - docker build -t $FRONT_END_REPO:latest ./nginx-container/
      - docker tag $FRONT_END_REPO:latest $FRONT_END_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker front end image...
      - docker push $FRONT_END_REPO:latest
      - docker push $FRONT_END_REPO:$IMAGE_TAG
