service: deleteAccount

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  timeout: 180
  environment:
    MAILGUN_API_KEY: ${file(secrets.json):MAILGUN_API_KEY}
    DBC_USERNAME: ${file(secrets.json):DBC_USERNAME}
    DBC_PASSWORD: ${file(secrets.json):DBC_PASSWORD}

functions:
  deleteAccount:
    handler: handler.deleteAccount
    timeout: 180
