export enum DeployFromGithubStateType {
  NOT_STARTED = 'NOT_STARTED',
  COMPILING_PROJECT_FROM_GITHUB = 'COMPILING_PROJECT_FROM_GITHUB',
  WAITING_FOR_GITHUB_AUTH = 'WAITING_FOR_GITHUB_AUTH',
  WAITING_FOR_GITHUB_RESPONSE = 'WAITING_FOR_GITHUB_RESPONSE',
  CHOOSING_GITHUB_REPO = 'CHOOSING_GITHUB_REPO',
  PUSHING_PROJECT_TO_GITHUB_REPO = 'PUSHING_PROJECT_TO_REMOTE_REPO',
  PROJECT_PUSHED_TO_GITHUB_REPO = 'PROJECT_PUSHED_TO_GITHUB_REPO',
  FINISHED = 'FINISHED'
}
