export enum NewGitRepoStateType {
  NOT_STARTED = 'NOT_STARTED',
  REPO_NOT_CREATED = 'REPO_NOT_CREATED',
  REPO_CREATED = 'REPO_CREATED',
  PROJECT_COMPILED = 'PROJECT_COMPILED',
  PROJECT_PUSHED = 'PROJECT_PUSHED'
}
