FROM node:10
# Note: Using Node 10 because it's the current LTS release and fabric doesn't work with odd numbers.

# Needed for node-gyp
RUN apt-get update
RUN apt-get install -y g++ build-essential

RUN mkdir /work/
RUN mkdir /work/front-end
RUN mkdir /work/front-end-modules
# It seems like it is safe to copy these files and then "mount" over them.
COPY ./package.json /work/front-end-modules/package.json
COPY ./package-lock.json /work/front-end-modules/package-lock.json
COPY ./remove-and-copy-npm-modules.sh /work/remove-and-copy-npm-modules.sh
WORKDIR /work/front-end-modules

# Necessary for certain modules to install correctly (mostly fabric).
RUN npm install -g node-gyp

RUN npm install

WORKDIR /work/front-end

# The "serve" mode will hot-reload components and watch for changes automatically.
ENTRYPOINT ["/work/remove-and-copy-npm-modules.sh"]
