service: processIncomingLambdaExecutionMetadata

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  timeout: 60
  environment:
    WEBHOOK_URL: ${env:WEBHOOK_URL}
    SERVICE_SHARED_SECRET: ${self:custom.service_shared_secret.SERVICE_SHARED_SECRET}

functions:
  lambdaHandler:
    handler: lambda_function.lambda_handler
    timeout: 60
    events:
      - stream:
          arn: ${env:KINESIS_STREAM_ARN}
          batchSize: 5000
          batchWindow: 60
          startingPosition: LATEST
          maximumRetryAttempts: 10
          enabled: true

custom:
    service_shared_secret: ${ssm:/aws/reference/secretsmanager/service_shared_secret~true}
