service: processIncomingLambdaExecutionMetadata

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  timeout: 60
  environment:
    WEBHOOK_URL: https://webhook.site/d1a311c1-5e1a-42e0-8ca6-0a84293fbd3b
    SERVICE_SHARED_SECRET: ${self:custom.service_shared_secret.SERVICE_SHARED_SECRET}

functions:
  lambdaHandler:
    handler: lambda_function.lambda_handler
    timeout: 60
    events:
      - stream:
          arn: arn:aws:kinesis:region:XXXXXX:stream/foo
          batchSize: 100
          startingPosition: LATEST
          maximumRetryAttempts: 10
          enabled: false

custom:
    service_shared_secret: ${ssm:/aws/reference/secretsmanager/service_shared_secret~true}
