secrets:
  awsAccessKeyID: {REFINERY_AWS_ACCESS_KEY_ID}
  awsSecretAccessKey: {REFINERY_AWS_SECRET_ACCESS_KEY}
  serviceSharedSecret: {SERVICE_SHARED_SECRET}
  mailgunApiKey: {MAILGUN_API_KEY}
  cookieSecretValue: {COOKIE_SECRET_VALUE}
  stripeApiKey: {STRIPE_API_KEY}
  intercomHMACSecret: {INTERCOM_HMAC_SECRET}
  githubClientID: {GITHUB_CLIENT_ID}
  githubClientSecret: {GITHUB_CLIENT_SECRET}

aws:
  accountID: {REFINERY_AWS_ACCOUNT_ID}

postgresql:
  postgresqlPassword: {POSTGRESQL_PASSWORD}
