service: processIncomingLambdaExecutionMetadata

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  timeout: 60
  environment:
    WEBHOOK_URL: https://webhook.site/d1a311c1-5e1a-42e0-8ca6-0a84293fbd3b
    

functions:
  lambdaHandler:
    handler: lambda_function.lambda_handler
    timeout: 60
