service: builder-functions

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  versionFunctions: false

plugins:
  - serverless-vpc-plugin

package:
  individually: true
  excludeDevDependencies: true

custom:
  vpcConfig:
    cidrBlock: "10.0.0.0/16"
    createNatInstance: true
    zones:
      - us-west-2a
    services:
      - s3
      - elasticfilesystem

functions:
  serverless-framework-builder:
    runtime: nodejs12.x
    handler: index.lambdaHandler
    timeout: 900
    fileSystemConfig:
      localMountPath: /mnt/efs
      arn:
        "Fn::GetAtt":
        - "EFSAccessPoint"
        - "Arn"
    dependsOn:
      - EFSMountTarget1
      - EFSMountTarget2
    role: ExampleLambdaRole

resources:
  - ${file(resources/iam_cf.yaml)}
  - ${file(resources/efs_cf.yaml)}
  - ${file(outputs/outputs.yaml)}
