apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01URXhNekl4TlRnek5Gb1hEVE13TVRFeE1USXhOVGd6TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1pjCjlkVUI5SnFDZzR2V3NuNWcrbkUvbnRVcmliUUJrUnIzYW8rUVI5YU9BUUV3L3FJTlFkTk9hZ2ZuR3p0bmpaVGwKRWtuTFRZMGZMK3VTQVUxTmlvcytnbnpYbmF4UU9FUzZUYXZrbkVyVFZQNWIvNWpWc2VMTEp3cEFJUDRoUVg5cgovd1RqSWhVcEtveUMyZ2lSbDJHUGFiOUQzWUtsbE84eUNFb2ZYdUJsVE9tVGpRck93b3pETldTVCtUTFZ2YXkzCk5tN0l6WnhjYkZ1SzBoMG1HK3dpTmxuYVB6ZFVnTXpJSzZlekpyZkg3S1E5K05URlNITnpWL2ZmeUVWWEpZTk0KMkZxZGFCMFpmV1d0U0ZXQnA5LzVaTm5EK0xObXB0bWR2cjlzZ2MvK1ROTGVpTWNXM3NUUmZhWnQyN2pZbW5xYgpiZ0lWVU5HZnRxNG13RERIS05rQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJRUhXeW40SVk2VUdTbXRJdWdlalh5a2xXYUQKc1hGakNhalBzYVBZRnJqdmtobmQ4bk1iZnRudXF5OTRvTXBhdjNzQ0ZnSUVGK1QzYVd1enhSRURLQ0x6Y1BmTwovekloZ0NKN0c5bmxObEFoZmVYSVZheXppelFPNnQ3cFBRTVFFZjZVSlp4ZVpZc0lqL2Q5UHRnbnlQQndpWlB5Ck9xZWZJWDN2bWNuM0xLQVM0ck5ibThvRVFiZmVZaE1HUnN3Qi9PZ1Z3a2p3bkhIaFpNUjg0b2NaUGZBK2JKbmwKdVc3cDFlOXN5bm82Yysvd3ZYWU9xdlBQMEdQK2pYOCtkRStqNWwzcnJrU1Z0VlZlMm4rdnlQc1RpS2lPUlREeApwRTA4L3lPOWk4aXJUUzZHQzBQWmZaN0llSVlRTjJiZTA1WFVOZnVSaXN0SWIzZEt4QmIrb3c5UDl5TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://3FB2EF914783C130E29FA96526097364.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:134071937287:cluster/refinery
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:134071937287:cluster/refinery
    user: arn:aws:eks:us-west-2:134071937287:cluster/refinery
  name: arn:aws:eks:us-west-2:134071937287:cluster/refinery
current-context: arn:aws:eks:us-west-2:134071937287:cluster/refinery
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:134071937287:cluster/refinery
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - refinery
      command: aws
