apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: refinery-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: refinery-operator-binding
subjects:
- kind: ServiceAccount
  name: refinery-sa
  namespace: refinery
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: refinery-operator
  apiGroup: rbac.authorization.k8s.io

